@api = http://localhost:3050/api/v1/prod-serv
#@api = http://187.229.22.99:8010/api/v1/prod-serv
### GET
GET {{api}}
### GET ITEM
GET {{api}}/1
### GET ITEM
GET {{api}}/1?keyType=OK
### GET ITEM
GET {{api}}/15058?keyType=BK